import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { StoreProvider } from "@/store/storeProvider";
import SessionProvider from "./providers";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()
  return (
    <StoreProvider>
    <html lang="en">
        <SessionProvider session={session}>
          <body className={inter.className}>{children}</body>
        </SessionProvider>
    </html>
    </StoreProvider>
  );
}
